apiVersion: v1
kind: ConfigMap
metadata:
  name: nestjs-k8s-env
data:
  PORT: "3000"
  NODE_ENV: "production"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "nestjs"
