apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-k8s
  template:
    metadata:
      labels:
        app: nestjs-k8s
    spec:
      containers:
        - name: nestjs-k8s
          image: armanalam/nestjs-k8s
          ports:
            - containerPort: 3000
          envFrom: #reference to the configMap
            - configMapRef:
                name: nestjs-k8s-env
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
