apiVersion: v1
kind: Service
metadata:
  name: nestjs-k8s
spec:
  selector:
    app: nestjs-k8s
  type: NodePort #can be LoadBalancer or ClusterIP (default)
  ports:
    - protocol: TCP
      port: 3000 #port for the service
      targetPort: 3000 #port for the container
      nodePort: 30080
